### ISSUE TITLE
bug in backup?

### ISSUE THREAD

**Issue by TheTesla** [veggiemonk/ansible-ohmyzsh#1]
fatal: [gdv-lenovo-y700.informatik.tu-chemnitz.de]: FAILED! => {"changed": true, "cmd": "if [ -f ~/.zshrc ]; then mv ~/.zshrc{,.orig}; fi", "delta": "0:00:00.002186", "end": "2016-09-15 14:48:34.297817", "failed": true, "invocation": {"module_args": {"_raw_params": "if [ -f ~/.zshrc ]; then mv ~/.zshrc{,.orig}; fi", "_uses_shell": true, "chdir": null, "creates": null, "executable": null, "removes": null, "warn": true}, "module_name": "command"}, "rc": 1, "start": "2016-09-15 14:48:34.295631", "stderr": "mv: Fehlender Zieldatei‐Operand hinter '/home/gdv/.zshrc{,.orig}'\n„mv --help“ liefert weitere Informationen.", "stdout": "", "stdout_lines": [], "warnings": []}

**Comment by veggiemonk** [comment]
There is a problem with the shell command. Probably that there is no `~/.zshrc` file...
